### ISSUE TITLE
Adding a note - double red light problem

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#12]
When adding a new note in `toggle mode` (AKA `play mode`), we can change the note of the new added note quickly now. However, when we change the note the old note light stays red so the keybed seems to indicate two notes are playing at once when it is just the second note pressed.

To replicate:
1. Enter `toggle/play mode` (top right button `amber`) 
2. Add a note 
3. Notice that middle C is highlight red
4. Press any note that is not middle C
5. Notice middle C is still red while the other note is also red

**Comment by mulshine** [comment]
Right, this is a mode swithing issue. After returning to edit note more
than once, the appropriate pitch (only) is displayed.
