### ISSUE TITLE
Assign trigger steps across/between sequencers

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#33]
Do we want to be able to do this?

**Comment by spiricom** [comment]
Not sure I understand - do you mean in between pages in full mode (i.e. not split mode)?
-Jeff

**Comment by JoshuaStorm** [comment]
I'm cleaning up the issues right now:

@mulshine @spiricom is this a thing I should keep as an issue? I kinda have no clue what this is

**Comment by mulshine** [comment]
keep for now, ill check on it

**Comment by mulshine** [comment]
we good
