### ISSUE TITLE
Remove function pointer style C

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#48]
I think me and @mulshine are in agreement that the non-function pointer style of pseudo-object oriented C works better. 

**I'm cool doing the leg work on this** cus I kinda like cleaning up code and it gives me something to do when I get stuck on something else. 

I propose these rules for our pseudo objects, feel free to disagree and we'll duke it out:

1. Prepend every function name with the module name and _: e.g. `myNoteStack.getSize(myNoteStack)` becomes `Notestack_getSize(myNoteStack)`
2. Have pseudo constructors: e.g. `Notestack_new()`
3. Not forgetting to also incldue `Notestack_free(myNoteStack)`
4. Have getters and setters as necessary: `myNoteStack->notestack` becomes `Notestack_getStack(myNoteStack)`. This allows us to only use functions exposed ("hiding" all the internal struct stuff) in the .h and be super cool modular dudes
5. With the above, typedefs become based on the pointer and not the struct itself, because this allows us to abstract our pseudo objects and treat them like normal objects (ie. not have to think about whether or not something is actually a pointer because we just pass it around to functions as it were an object). This is also kinda the more standard thing to do in C
6. We should use enums in some places where macro defines are used (like rangemode and togglemode flags)

**Comment by JoshuaStorm** [comment]
Also, sans disagreements, bring up anything that you think I left out

**Comment by mulshine** [comment]
this all sounds good, though i'd be wary of any dynamic memory allocation
in Notestack_new() and _free(). on a lot of platforms (including
stm32f4/f7) C stdlib dynamic memory allocation (malloc, calloc, free) is
basically unsupported (as we learned the hard way making our
microcontroller-tailored audio library in C). for the most part, people
don't try to allocate memory at runtime in embedded applications -
everything is statically allocated. Jeff, feel free to confirm or
disagree...

Josh, before we do this reconfiguration, let's chat about it (especially a
la 2 through 5 above). Feel free to go at the renaming of functions and
removal of function pointers though (1) and obvs number 6.

mike

**Comment by JoshuaStorm** [comment]
Totally forgot about thaaattt. I might need to do some research into best practices for embedded stuffs. Thanks for giving this a read through
