### ISSUE TITLE
Trigger mode weirdness

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#51]
Hard to describe this problem so:

1. Go into trigger mode, now you're in toggle mode
2. Exit the menu (bottom left button)
2. Hit top right button, entering edit mode
3. Hit top right button again, entering trigger toggle mode
4. This turns the top right button red, and the bottom left button red supposedly to indicate entering the menu? But this doesn't open the menu, the trigger mode interface is still shown
5. Hit top right button again, going back into toggle mode. Notice the bottom left button is still red, and this time it actually enter the menu.

Not sure what of this is supposed to happen and what is just totally wonky

**Comment by mulshine** [comment]
think i know whats up no worries.
