### ISSUE TITLE
sequencer.getHexFromStep is used a couple of times... getHexFromStep function doesn't exist

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#52]
~~Noticed this while refactoring. Due to how we were doing function pointers, errors weren't being thrown for calling a function that did not exist.~~

~~At the moment, I'm not certain what this actually effects, it seems to be only used in range mode.~~

OOPS

**Comment by JoshuaStorm** [comment]
To clarify: the sequencer struct had a member called getHexFromStep, but this was never assigned to in the initializer

**Comment by JoshuaStorm** [comment]
Oh wait oops, this is because I implemented it in my other PR. 

ooops

**Comment by mulshine** [comment]
hmm thats the function that we were trying to implement to get range mode
working with other step patterns.

**Comment by mulshine** [comment]
ahh yes i thought it existed ;) not initializing the pointer is common
problem, another reason we should do away with that notation asap
