### ISSUE TITLE
Thing we should definitely do...

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#57]
Badass LED pattern/sequencer/LOGO/MM/something on startup!! :D crazy light stuffz for fun (and so user is confident thing is workin.)

**Comment by mulshine** [comment]
of course it should visually sequence our names (one letter per frame)...... lol

**Comment by JoshuaStorm** [comment]
Top priority to this issue

**Comment by spiricom** [comment]
Overruled!

**Comment by spiricom** [comment]
Sounds too fun
