### ISSUE TITLE
Keyboard Mode

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#62]
Buttons...
TopL - Octave down
TopR - Octave up
BotL - Options Mode
BotR - Shift top buttons to Up/Down semitone

Sliders...
Top - CV1  - or pitch bend if shift is pressed
Bot - CV2 - or fine tune if shift is pressed??

Keyboard layout...
For now, limited to ~10 pre-defined keyboard layouts
Later, allow user to edit and save keyboard layouts

**Comment by spiricom** [comment]
I just edited the top comment to reflect our current ideas of the functionality we are aiming for

**Comment by mulshine** [comment]
different now
