### ISSUE TITLE
Combining Sequencer and Keyboard Presets?

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#66]
It would be easy to allow simultaneous Pitch or Trigger Sequencer and 2-voice Keyboard mode, right? 

Come to think of it, this could be built in to the Manta/MantaMate UI even...

**Comment by JoshuaStorm** [comment]
Ooohhhhh I like the sound of this

**Comment by JoshuaStorm** [comment]
This seems to be implemented now
