### ISSUE TITLE
PRESS PRESET BUTTON ON STARTUP!!

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#68]
Good news:  I got Modes 00-04 working well... i.e Sequencer and mono-tetra phonic Keyboard modes. 

(Bad) news: One bug, NEED TO HIT PRESET BUTTON ON MANTAMATE STARTUP TO ENTER PRESET 00 (ie Sequencer). Just putting this out there so someone doesn't go thinking it's broken when no lights are lit up on the MM and waste a bunch of timeeeee !!!!

**Comment by spiricom** [comment]
Josh and I fixed this a while ago but forgot to close this issue :)
