### ISSUE TITLE
KeyboardMode combined with Sequencers

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#70]
Instead of Sequencer 1 and Sequencer 2, we have  Left and Right views. Each page can be either a Pitch Sequencer, Trigger Sequencer, or Keyboard (monophonic or duophonic). A separate Keyboard-only option will exist for Quadraphonic and Triophonic will no longer exist.

This allows dual Mono- and Duo-phonic and a bunch of Sequencer-Keyboard combinations.

**Comment by mulshine** [comment]
Proposals for new UpperHexUI  (upper two rows) for clear representation of Left and Right pages and their states... This menu would show up in any mode (PitchSeq/TrigSeq/Keyboard) while the top two function buttons are pressed. 

Possibility number 1...
TopRow
1 - Switch L
2 - Switch R
3 -
4 - 
5 - 
6 - 
7 - 
8 -

BottomRow
1 - Set L Sequencer/Keyboard.
2 - If Sequencer, set Pitch/Trigger. If Keyboard, set Mono/Duo.
3 - Set R Sequencer/Keyboard.
4 - If Sequencer, set Pitch/Trigger. If Keyboard, set Mono/Duo.
5 - If L and R both Sequencers, set Full/Split. If L and R both Keyboard, set (Mono|Duo)/Quad.
6 - 
7 - 
8 -

Possibility number 2...
TopRow
1 - Switch L
2 - Switch R
3 - 
4 - 
5 -  If L and R both Sequencers, set Full/Split. If L and R both Keyboard, set (Mono|Duo)/Quad.
6 - 
7 - 
8 -

BottomRow (only one of the 1-4 and one of the 5-8 hexes can be toggled at any time)
1 - L Mono
2 - L Duo
3 - L PitchSeq
4 - L TrigSeq
5 - R Mono
6 - R Duo
7 - R PitchSeq
8 - R TrigSeq

**Comment by mulshine** [comment]
im kind of leaning towards number 2...

**Comment by JoshuaStorm** [comment]
Implemented!
