### ISSUE TITLE
fill random sequences feature

### ISSUE THREAD

**Issue by spiricom** [spiricom/MantaMate#76]
It would be very useful to have some button combination that will fill all of the possible sequencer stages with random material. I think this would be great both for rhythmic trigger stuff and for pitched things. Not sure how it would be activated, though. Maybe another thing where you hold down "menu" but you press the top right button along with it?

**Comment by mulshine** [comment]
yeah this would be great! adding it to the github issue for MM todo

**Comment by spiricom** [comment]
We now are thinking of having this be a situation where you press right top button to enter edit mode and also press top left. This would enter "randomize edit" mode, where when you touch something to edit something it actually randomizes it. 
There would also be a "randomize" hexagon next to the blank hexagon in the composition row, which alters the current local sequence to introduce a percent of randomness. Applied on hex release. During hex press, you can adjust the slider to set how dramatic the randomize is.
