### ISSUE TITLE
removing range mode?

### ISSUE THREAD

**Issue by spiricom** [spiricom/MantaMate#79]
I'm considering removing range mode altogether. That would make it faster to switch between toggle mode and arpeggiator mode, which I think are the more important modes, since you won't have to cycle through three separate modes. What do you guys think? I'm finding it less useful than it is on the JD-1, where I use it all the time. On the Manta, where the sensors are not linear, it makes less sense, and I mostly engage with it by mistake while trying to use arpeggiator mode.

**Comment by JoshuaStorm** [comment]
Also not a huge fan of range mode and think decluttering UI is more important than a mode that can mostly be reproduced with other modes

**Comment by mulshine** [comment]
down to get rid of it
