### ISSUE TITLE
needs better UP/DOWN pushbutton handling

### ISSUE THREAD

**Issue by spiricom** [spiricom/MantaMate#83]
I need to do better debouncing (occasionally jumps two values or doesn't go where I want), and also need to add functionality to somehow go faster (long hold starts jumping by 10 or scanning quickly?)

**Comment by spiricom** [comment]
Fixed! Might be able to improve the debouncing a little more, but it's better now, and the quick scan works nicely.

**Comment by mulshine** [comment]
sweet!
