### ISSUE TITLE
exiting options mode doesn't reset LEDs for sequences correctly 

### ISSUE THREAD

**Issue by spiricom** [spiricom/MantaMate#84]
often the "clear" button hangs on, and when loading a composition the toggled leds are incorrect

**Comment by mulshine** [comment]
yeah ive gotten that a few times too. wasnt too careful about mode
switching when first implementing it and didnt want to bother. but will fix
as soon as i get back to it!

**Comment by mulshine** [comment]
dont think this is still an issue
