### ISSUE TITLE
Random internal clock mode would be nice

### ISSUE THREAD

**Issue by spiricom** [spiricom/MantaMate#88]
I will try to implement something where if you go above 9 in the clock divider settings, you get 9 more options which are for different random clock styles.

**Comment by mulshine** [comment]
sweet! i wonder if it would be fun to throw in some typical tempo/rhytmic
patterns, like shuffle or (*cringing*) swing

**Comment by spiricom** [comment]
da dutda da dutda da dutda da

**Comment by spiricom** [comment]
DONE!
