### ISSUE TITLE
Mode to turn slider control DAC outputs to drum triggers

### ISSUE THREAD

**Issue by JoshuaStorm** [spiricom/MantaMate#9]
It'd be cool if we could have a drum sequencer alongside the pitched sequencer. However, this would require using the DAC outputs usually used for the slider CVs. 

This was just a thought I had, and should definitely be a "everything else is done already, so let's just add this for lols" type thing.

**Comment by spiricom** [comment]
I thought a bit about this, and it shouldn't actually be a problem, -- we could make it so it's another type of "dual mode" - the middle 16 turn into the rhythm thing, the bottom 16 are still pitched, and then we have 4 outputs to use for the gates - although I guess we only have space to have one 16-beat pattern... I guess we could have those middle 16 represent one of four rhythm sequences, and you could page through which one you're looking at...  Still easier to conceptualize it if we keep the rhythm sequencer separate.

**Comment by JoshuaStorm** [comment]
Super outdated issue
